# GITHUB_PAT=ghp_xxxxxxx docker compose up --build
version: '3.8'

services:
  elasticsearch:
    build:
      context: ./src/elasticsearch
    container_name: elasticsearch
    ports:
      - "9200:9200"
    volumes:
      - data:/usr/share/elasticsearch/data
      - logs:/usr/share/elasticsearch/logs
    mem_limit: 1g
    cpus: 1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200/_cluster/health/"]
      interval: 30s
      timeout: 10s
      retries: 5

  grafana:
    build:
      context: ./src/grafana
    container_name: grafana
    mem_limit: 1g
    cpus: 0.5
    ports:
      - "3000:80"
    depends_on:
      - elasticsearch
    volumes:
      - grafana:/var/lib/grafana
    environment:
      GF_LOG_LEVEL: debug
      GF_SERVER_HTTP_PORT: 80
      GF_SECURITY_ADMIN_USER: demouser
      GF_SECURITY_ADMIN_PASSWORD: Sicherheit@1512
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/api/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  init-grafana:
    mem_limit: 0.5g
    cpus: 0.25
    build:
      context: ./src/cpuad-updater/grafana
    container_name: init-grafana
    depends_on:
      - grafana
      - elasticsearch
      - cpuad-updater
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      GRAFANA_URL: http://grafana:80
      GRAFANA_USERNAME: demouser
      GRAFANA_PASSWORD: Sicherheit@1512
    restart: "no"

  cpuad-updater:
    mem_limit: 0.5g
    cpus: 0.25
    build:
      context: ./src/cpuad-updater
    container_name: cpuad-updater
    depends_on:
      - elasticsearch
    environment:
      GITHUB_PAT: ${GITHUB_PAT}
      ORGANIZATION_SLUGS: ms-mfg-community
      ELASTICSEARCH_URL: http://elasticsearch:9200
      # Add other environment variables as needed
    restart: "no"

volumes:
  data:
  logs:
  grafana: